language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install -y libsundials-serial-dev;

install:
  - pip install hypothesis
  # install dependencies.
  - pip install .

script:
  - pytest