language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - pip install -e git://github.com/pints-team/pints.git#egg=pints

install:
  - pip install hypothesis
# reqs for myokit below
  - pip install scipy sympy pyqt5 matplotlib
  - pip install myokit
  - sudo apt-get install libsundials-serial-dev
# reqs for pints below
  - pip install numpy cma tabulate

script:
  - pytest