language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install unittest, hypothesis
# reqs for myokit below
  - pip install scipy, sympy, pyqt5, matplotlib
  - apt-get install libsundials-dev
  - pip install myokit
# reqs for pints below
  - pip install numpy, cma, tabulate

script:
  - python -m unittest discover test